### ISSUE TITLE
程序出问题了？请修正

### ISSUE THREAD

**Issue by VPN-V2Ray** [pyfbsdk59/Python-ChatGPT-TelegramBot-Vercel#1]
测试了一下，刚开始可以用，后面发几个消息就没有回复了。看了一下运行日志显示如图
![photo_2023-02-17_13-39-00](https://user-images.githubusercontent.com/46552880/219558928-7676edde-b9a2-471e-99ab-fd36bff94476.jpg)

**Comment by pyfbsdk59** [comment]
This may be due to the reason that too many people are using the ChatGPT service, and the serverless function service of Vercel can't get the response within 10 seconds, which is the limit of the free plan.
